name: hafilatuna
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_svg: ^2.0.7
  retrofit: '>=4.0.0 <5.0.0'
  json_annotation: ^4.8.0
  logger: ^1.4.0
  flutter_secure_storage: ^8.0.0
  flutter_spinkit: ^5.1.0
  url_launcher: ^6.1.12
  card_stack_widget: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: ^6.0.0
  build_runner: ">2.3.0 <4.0.0"
  json_serializable: ">4.4.0"
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
